replicaCount: 1
image:
  repository: 194636597980.dkr.ecr.eu-central-1.amazonaws.com/url-shortener-repo
  pullPolicy: Always 
  tag: "latest"

secrets:
  enabled: true
  name: "my-secure-shortener-db-pass" 

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

probes:
  liveness:
    path: /health
  readiness:
    path: /health