apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "url-shortener.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*" 
    tls:
      mode: SIMPLE
      credentialName: istio-ingressgateway-certs 
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "url-shortener.fullname" . }}-routing
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "url-shortener.fullname" . }}-gateway
  http:
  - match:
    - uri:
        prefix: /oauth2
    route:
    - destination:
        host: oauth2-proxy.istio-system.svc.cluster.local
        port:
          number: 4180
  - match:
    - uri:
        prefix: /grafana
    route:
    - destination:
        host: monitoring-grafana.monitoring.svc.cluster.local
        port:
          number: 80
  - route:
    - destination:
        host: {{ include "url-shortener.fullname" . }}
        port:
          number: {{ .Values.service.port }}