apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "url-shortener.fullname" . }}-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.name }}" # השם שנתת בטראפורם
        objectType: "secretsmanager"
        jmesPath: 
          - path: "password"
            objectAlias: "db-password"
  # זה יוצר Kubernetes Secret אמיתי מה-AWS Secret
  secretObjects:
    - secretName: url-shortener-secrets
      type: Opaque
      data:
        - objectName: db-password
          key: db-password