# name: CI Pipeline

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   ci-lifecycle:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: '0'
      
#       # - name: Configure AWS credentials
#       #   uses: aws-actions/configure-aws-credentials@v2
#       #   with:
#       #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       #     aws-region: ${{ secrets.AWS_REGION }}
      
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.9'

#       - name: Install dependencies
#         run: |
#           pip install -r app/requirements.txt
#           pip install flake8 pytest pytest-cov
      
      
#       # - name: Login to Amazon ECR
#       #   id: login-ecr
#       #   uses: aws-actions/amazon-ecr-login@v1

#       # --- Static Code Analysis (Linting) ---
#       - name: Run Linting
#         run: |
#           # Quality Gate
#           flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics

#       # --- Unit Tests & Coverage (Quality Gate 1) ---
#       - name: Run Unit Tests
#         run: |
#           # Quality Gate
#           export PYTHONPATH=$PYTHONPATH:$(pwd)/app
#           pytest app/test_main.py --cov=app --cov-fail-under=80

#       # --- (Semantic + SHA) ---
#       - name: Bump version and push tag
#         id: tag_version
#         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#         uses: anothrNick/github-tag-action@1.64.0
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           INITIAL_VERSION: 1.0.0
#           DEFAULT_BUMP: patch
#           WITH_V: false
#           MAJOR_STRING_TOKEN: "#MAJOR"
#           MINOR_STRING_TOKEN: "#MINOR"

#       - name: Prepare Tag
#         id: vars
#         run: |
#           SHA=$(echo ${GITHUB_SHA} | cut -c1-7)
#           if [ "${{ github.event_name }}" == "pull_request" ]; then
#             echo "tag=pr-${{ github.event.number }}-${SHA}" >> $GITHUB_OUTPUT
#           else
#             echo "tag=${{ steps.tag_version.outputs.new_tag }}-${SHA}" >> $GITHUB_OUTPUT
#           fi

#       # --- Build Docker Image ---
#       - name: Build Docker Image
#         run: docker build -t url-shortener:${{ steps.vars.outputs.tag }} .

#       # --- Security Scan (Quality Gate 2) ---
#       - name: Scan Image (Trivy)
#         uses: aquasecurity/trivy-action@master
#         with:
#           image-ref: 'url-shortener:${{ steps.vars.outputs.tag }}'
#           format: 'table'
#           exit-code: '1'
#           severity: 'CRITICAL,HIGH'
#           trivyignore: .trivyignore

#       # # --- Push to Registry (Main) ---
#       # - name: Push Image
#       #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#       #   run: |
#       #     echo "Pushing image to registry with tag ${{ steps.vars.outputs.tag }}..."
#       #     # docker push my-registry/url-shortener:${{ steps.vars.outputs.tag }}

name: CI/CD Pipeline

on:
  push:
    branches: [ main  , feature/initial-setup ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy-infra:
    name: Build & Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-eks-deployer
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3 
        with:
          terraform_version: 1.7.0
        
      - name: Terraform Init & Workspace & Apply
        run: |
          cd terraform
          terraform init
          
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            WORKSPACE="prod"
          else
            WORKSPACE="stage"
          fi
          
          terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE
          terraform apply -auto-approve

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.ref == 'refs/heads/main' && 'url-shortener-prod-repo' || 'url-shortener-stage-repo' }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Install Secrets Store CSI Driver
        run: |
          CLUSTER_NAME=${{ github.ref == 'refs/heads/main' && 'url-shortener-prod' || 'url-shortener-stage' }}
          aws eks update-kubeconfig --region eu-central-1 --name $CLUSTER_NAME
                    
          helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts --force-update
          helm repo update
          
          helm upgrade --install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver \
            --namespace kube-system \
            --set syncSecret.enabled=true \
            --set enableSecretRotation=true \
            --wait

      # --- ISTIO & MONITORING INSTALLATION ---
      - name: Generate SSL Certificate
        run: |
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
            -keyout tls.key -out tls.crt \
            -subj "/CN=url-shortener.local"
          kubectl create namespace istio-system --dry-run=client -o yaml | kubectl apply -f -
          kubectl create secret tls istio-ingressgateway-certs --key tls.key --cert tls.crt -n istio-system --dry-run=client -o yaml | kubectl apply -f -

      - name: Install Istio & OAuth2 Proxy
        run: |
          # Istio
          helm repo add istio https://istio-release.storage.googleapis.com/charts
          helm repo add oauth2-proxy https://oauth2-proxy.github.io/manifests
          helm repo update
          helm upgrade --install istio-base istio/base -n istio-system --create-namespace
          helm upgrade --install istiod istio/istiod -n istio-system --wait
          helm upgrade --install istio-ingressgateway istio/gateway -n istio-system \
            --set service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="external" \
            --set service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-nlb-target-type"="instance" \
            --set service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-scheme"="internet-facing" \
            --wait --timeout 15m

          # OAuth2 Proxy
          helm upgrade --install oauth2-proxy oauth2-proxy/oauth2-proxy \
            --namespace istio-system \
            --set config.clientID=${{ secrets.OAUTH_CLIENT_ID }} \
            --set config.clientSecret=${{ secrets.OAUTH_CLIENT_SECRET }} \
            --set config.cookieSecret=${{ secrets.OAUTH_COOKIE_SECRET }} \
            --set extraArgs.provider=github \
            --set extraArgs.github-user="MrJoRnO" \
            --set extraArgs.upstream=file:///dev/null \
            --set extraArgs.http-address=0.0.0.0:4180 --wait

      - name: Install Monitoring Stack
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          
          LB_HOST=$(kubectl get svc istio-ingressgateway -n istio-system -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          
          helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
            --namespace monitoring --create-namespace \
            --set grafana."grafana\.ini".server.root_url="https://$LB_HOST/grafana/" \
            --set grafana."grafana\.ini".server.serve_from_sub_path=true \
            --wait --timeout 15m

  deploy-staging:
    name: Deploy to Staging
    needs: build-and-deploy-infra
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-eks-deployer
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr-staging
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region eu-central-1 --name url-shortener-stage
          kubectl create namespace staging --dry-run=client -o yaml | kubectl apply -f -
          kubectl label namespace staging istio-injection=enabled --overwrite

      - name: Deploy to Staging with Helm
        run: |
          REGISTRY="${{ steps.login-ecr-staging.outputs.registry }}"
          REPOSITORY="url-shortener-stage-repo"
          
          LATEST_SECRET=$(aws secretsmanager list-secrets --query 'SecretList[?starts_with(Name, `url-shortener-stage-db-pass-`)].Name' --output text | tr '\t' '\n' | sort -V | tail -n 1)
          echo "Found latest secret: $LATEST_SECRET"

          helm upgrade --install staging-app ./helm/url-shortener \
            -f ./helm/url-shortener/values.yaml \
            -f ./helm/url-shortener/values-staging.yaml \
            --set image.repository=$REGISTRY/$REPOSITORY \
            --set image.tag=${{ github.sha }} \
            --set secrets.aws_secret_name=$LATEST_SECRET \
            --namespace staging \
            --create-namespace --wait --timeout 15m
      
      - name: Get NLB Address
        run: |
          echo "Waiting for NLB to provision..."
          for i in {1..10}; do
            LB_HOST=$(kubectl get svc istio-ingressgateway -n istio-system -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
            if [ -n "$LB_HOST" ]; then
              echo "===================================================="
              echo "🚀 YOUR NLB ADDRESS IS: $LB_HOST"
              echo "===================================================="
              break
            fi
            echo "Still waiting..."
            sleep 15
          done

  deploy-prod:
    name: Deploy to Production
    needs: build-and-deploy-infra
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-eks-deployer
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr-prod 
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region eu-central-1 --name url-shortener-prod
          kubectl create namespace prod --dry-run=client -o yaml | kubectl apply -f -
          kubectl label namespace prod istio-injection=enabled --overwrite

      - name: Deploy to Production with Helm
        run: |
          REGISTRY="${{ steps.login-ecr-prod.outputs.registry }}"
          REPOSITORY="url-shortener-prod-repo"
          
          LATEST_SECRET=$(aws secretsmanager list-secrets --query 'SecretList[?starts_with(Name, `url-shortener-prod-db-pass-`)].Name' --output text | tr '\t' '\n' | sort -V | tail -n 1)
          
          helm upgrade --install prod-app ./helm/url-shortener \
            -f ./helm/url-shortener/values.yaml \
            -f ./helm/url-shortener/values-production.yaml \
            --set image.repository=$REGISTRY/$REPOSITORY \
            --set image.tag=${{ github.sha }} \
            --set secrets.aws_secret_name=$LATEST_SECRET \
            --namespace prod \
            --create-namespace --wait --timeout 5m
      
      - name: Get NLB Address
        run: |                              
          echo "Waiting for NLB to provision..."
          for i in {1..10}; do
            LB_HOST=$(kubectl get svc istio-ingressgateway -n istio-system -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
            if [ -n "$LB_HOST" ]; then
              echo "===================================================="
              echo "🚀 YOUR NLB ADDRESS IS: $LB_HOST"
              echo "===================================================="
              break
            fi
            echo "Still waiting..."
            sleep 15
          done